# Generated by Django 3.0.7 on 2023-11-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forus_Webapp', '0003_auto_20231103_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockbin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ERP_NO', models.CharField(max_length=60)),
                ('MP_NO', models.CharField(max_length=60)),
                ('store', models.CharField(max_length=60)),
                ('device', models.CharField(max_length=60)),
                ('rack', models.CharField(max_length=60)),
                ('bin_card', models.CharField(max_length=60)),
                ('date', models.CharField(max_length=60)),
                ('pb', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=60)),
                ('no_received', models.CharField(max_length=60)),
                ('no_issue', models.CharField(max_length=60)),
                ('sb', models.CharField(max_length=60)),
                ('sv', models.CharField(max_length=60)),
                ('remarks', models.CharField(max_length=60)),
            ],
        ),
    ]
