# Generated by Django 3.0.7 on 2023-11-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forus_Webapp', '0004_stockbin'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbin',
            name='rdno',
            field=models.CharField(default=1, max_length=60),
        ),
    ]
