# Generated by Django 3.0.7 on 2023-11-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forus_Webapp', '0006_additem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='additem',
        ),
    ]
