# Generated by Django 3.0.7 on 2023-11-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forus_Webapp', '0008_additem'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=60)),
                ('rkr', models.CharField(max_length=60)),
                ('devr1', models.CharField(max_length=60)),
                ('shelf', models.CharField(default='shelf1', max_length=60)),
                ('binr', models.CharField(max_length=60)),
            ],
        ),
    ]
