# Generated by Django 3.0.7 on 2023-11-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forus_Webapp', '0009_store_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbin',
            name='shelf',
            field=models.CharField(default=1, max_length=60),
        ),
    ]
