# Generated by Django 3.0.7 on 2023-11-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forus_Webapp', '0010_stockbin_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='Iss',
            field=models.CharField(default=1, max_length=60),
        ),
        migrations.AddField(
            model_name='additem',
            name='Rece',
            field=models.CharField(default=1, max_length=60),
        ),
        migrations.AddField(
            model_name='additem',
            name='cd',
            field=models.CharField(default=1, max_length=60),
        ),
        migrations.AddField(
            model_name='additem',
            name='db',
            field=models.CharField(default=1, max_length=60),
        ),
        migrations.AddField(
            model_name='additem',
            name='pd',
            field=models.CharField(default=1, max_length=60),
        ),
        migrations.AddField(
            model_name='additem',
            name='rm1',
            field=models.CharField(default=1, max_length=60),
        ),
    ]
