# Generated by Django 3.0.7 on 2023-11-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forus_Webapp', '0011_auto_20231118_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='deviceitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('total', models.CharField(max_length=60)),
                ('Previous_Date', models.CharField(default=1, max_length=60)),
                ('Received', models.CharField(default=1, max_length=60)),
                ('Issued', models.CharField(default=1, max_length=60)),
                ('Current_Date', models.CharField(default=1, max_length=60)),
                ('Device_Balance', models.CharField(default=1, max_length=60)),
                ('Remarks', models.CharField(default=1, max_length=60)),
            ],
        ),
    ]
