# Generated by Django 3.0.7 on 2023-11-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forus_Webapp', '0012_deviceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceitem',
            name='total',
        ),
    ]
