# Generated by Django 3.0.7 on 2023-11-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forus_Webapp', '0014_deviceitem_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceitem',
            name='Previous_Balance',
            field=models.CharField(default=1, max_length=60),
        ),
    ]
