# Generated by Django 3.0.7 on 2023-11-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forus_Webapp', '0015_deviceitem_previous_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stockbin',
        ),
    ]
