# Generated by Django 3.0.7 on 2023-11-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forus_Webapp', '0017_stockbin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stockbin',
        ),
    ]
