# Generated by Django 3.0.7 on 2023-11-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forus_Webapp', '0019_stockbin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbin',
            name='no_issue',
            field=models.CharField(default=0, max_length=60),
        ),
        migrations.AlterField(
            model_name='stockbin',
            name='no_received',
            field=models.CharField(default=0, max_length=60),
        ),
        migrations.AlterField(
            model_name='stockbin',
            name='pb',
            field=models.CharField(default=0, max_length=60),
        ),
        migrations.AlterField(
            model_name='stockbin',
            name='remarks',
            field=models.CharField(default='remark', max_length=60),
        ),
        migrations.AlterField(
            model_name='stockbin',
            name='sb',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
