# Generated by Django 3.0.7 on 2023-12-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forus_Webapp', '0021_stockbin_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbin',
            name='item',
            field=models.CharField(default=1, max_length=60),
        ),
    ]
