# Generated by Django 3.0.7 on 2024-05-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forus_Webapp', '0025_stock_bin_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock',
        ),
    ]
